<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    </head>
    <body>
        <div class="container text-center my-5">
            <h1>Share Code in Real-time with Developers</h1>
            <a href="/code/new" class="btn btn-dark">Create</a>
            <a href="/code/latest" class="btn btn-dark">latest code share</a>
        </div>

    </body>
</html>